MAX_ENCHANTMENT_TEXT = true
EASTER_EGGS = false

[ALL_GOBLIN_TRADERS_CONFIG]
FIND_COOLDOWN = 72000
FALL = true
NO_ATTACK_CREATIVE = true
CAN_BE_RESTOCKED = true
DISCARD_BAG = false
CAN_GET_KNOCKED_OUT = false
CAN_BE_LEASHED = true

[GOBLIN_TRADER_CONFIG]
CAN_SPAWN = true
HIT_BACK = false
SPAWN_CHANCE = 100
SPAWN_DELAY = 72000
MAX_SPAWN_HEIGHT = 50
MIN_SPAWN_HEIGHT = 0

[VEIN_GOBLIN_TRADER_CONFIG]
CAN_SPAWN = true
HIT_BACK = false
SPAWN_CHANCE = 100
SPAWN_DELAY = 72000
MAX_SPAWN_HEIGHT = 50
MIN_SPAWN_HEIGHT = 0
DAMAGED_IN_WATER = false
